# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20170724_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
