# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_author_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weblog.Blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('weblog.blog',),
        ),
    ]
