# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_themeblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weblog.Entry')),
            ],
        ),
    ]
